## Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
print(arr)
arr_slicing = arr[2:8]
print("sliced array : ", arr_slicing)
arr_slicing_step = arr[2:8:2]
print("sliced array with 2 step : ", arr_slicing_step)

#Negetive indexing

array = np.arange(12)
print(array)
print("Negative indexing find -4 : ", array[-4])

[ 0  1  2  3  4  5  6  7  8  9 10]
sliced array :  [2 3 4 5 6 7]
sliced array with 2 step :  [2 4 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Negative indexing find -4 :  8


In [3]:
arr_2d = np.array([[2,4,9],
                   [5,8,1],
                   [9,2,3]])
print("Printing specific element : ", arr_2d[1,2])
print("Printing specific row in the matrix : ", arr_2d[1])
print("Printing specific column : ", arr_2d[:,2]) #this means that : refers to the entire rows meaning all the rows and 
#after comma we are refering the column that we want to print

Printing specific element :  1
Printing specific row in the matrix :  [5 8 1]
Printing specific column :  [9 1 3]


## Sorting

In [4]:
unsorted_arr = np.array([1,24,12,34,9,6,32,54,32,2,7,21,11])
print("Sorted array using Numpy : ", np.sort(unsorted_arr)) #here we have sorted the array

unsorted_2d_arr = np.array([
    [2,4,5],
    [2,5,9],
    [8,9,4]])
print("This is the sorted format of 2D array : \n", np.sort(unsorted_2d_arr, axis=1))
# when the axis is 0 then it will sort the matrix row wise, and when the axis is 1 then it will sort column wise.


Sorted array using Numpy :  [ 1  2  6  7  9 11 12 21 24 32 32 34 54]
This is the sorted format of 2D array : 
 [[2 4 5]
 [2 5 9]
 [4 8 9]]


## Filter

In [5]:
numbers = np.array([2,3,5,1,8,4])
even_nums = numbers[numbers%2==0]
print("even numbers numpy way : ", even_nums)

#Filtering by mask

array_mask = numbers > 4
print("Show all the masked numbers by masking : \n", numbers[array_mask])

even numbers numpy way :  [2 8 4]
Show all the masked numbers by masking : 
 [5 8]


## Fancy Indexing and Numpy where clause

In [6]:
indices = [2,4,3,1] #These are the indexes 
print("printing the indices of numbers array :\n", numbers[indices])

where_res = np.where(numbers>3)
print(where_res)
print("NP Where result : ",numbers[where_res])

#using conditions with the np array and where clause

conditional_arr = np.where(numbers>5, numbers*5, numbers) #The parameter sequence is like (condition, what to do if it is true, else statement)
print("Conditional array output : \n",conditional_arr )

printing the indices of numbers array :
 [5 8 1 3]
(array([2, 4, 5]),)
NP Where result :  [5 8 4]
Conditional array output : 
 [ 2  3  5  1 40  4]


## Adding and removing data

In [7]:
arr1 = np.array([12,24,11])
arr2 = np.array([76,33,21])

combined = np.concatenate((arr1,arr2))
print(combined)

[12 24 11 76 33 21]


### Array Compatibility

In [8]:
a = np.array([2,54,54])
b = np.array([42,33,59])
c = np.array([25,4,5,6])

print("compatibility of the arrays check : ", a.shape == c.shape) #so here both the shapes are not equal

compatibility of the arrays check :  False


In [9]:
original = np.array([[12,55,34],[8,43,2],[2,54,12]])
new_row = np.array([4,9,2])

with_new_row = np.vstack((original,new_row))
print("Added New Row : \n", with_new_row)

Added New Row : 
 [[12 55 34]
 [ 8 43  2]
 [ 2 54 12]
 [ 4  9  2]]


In [10]:
new_col = np.array([[3],[5],[6]])
added_new_col = np.hstack((original,new_col)) #this will add a new column to the existing matrix, remember you have to provide the columns as individual 2D matrix format
print("Added new column to the matrix : \n", added_new_col)



Added new column to the matrix : 
 [[12 55 34  3]
 [ 8 43  2  5]
 [ 2 54 12  6]]


In [ ]:
#Deleting an element in an array
new_arr = np.array([12,44,12,22])
del_arr = np.delete(new_arr,2)

print("Array after deleting : \n", del_arr) #result -> [12 44 22] so the 2nd index is deleted succesfully

Array after deleting : 
 [12 44 22]


: 