## Advances operations with Business examples

In [3]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [5]:
# Data structure: [shop_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 25000, 30000, 33000, 36000],   # Book World
    [2, 28000, 32000, 34000, 37000],   # Toy Planet
    [3, 22000, 25500, 27000, 31500],   # Gadget Garage
    [4, 19000, 23000, 24500, 26500],   # Fashion Central
    [5, 33000, 35000, 37000, 40000]    # Sports Hub
])

print("===========Store Sales Analysis==========")
print(sales_data)


===========Store Sales Analysis==========
[[    1 25000 30000 33000 36000]
 [    2 28000 32000 34000 37000]
 [    3 22000 25500 27000 31500]
 [    4 19000 23000 24500 26500]
 [    5 33000 35000 37000 40000]]


In [ ]:
#First step should be to identify the shape of the data that you are working with
print(np.shape(sales_data)) # we got the result as (5, 5) which means its a 5x5 matrix

(5, 5)


In [ ]:
#Get the data of first 3 stores
first_3_stores = sales_data[:3]
# print("First 3 stores : ",first_3_stores)
print(sales_data[:,1:]) # so here 1st parameter represents the row and second parameter represents the column and will be manipulated accordingly.

[[25000 30000 33000 36000]
 [28000 32000 34000 37000]
 [22000 25500 27000 31500]
 [19000 23000 24500 26500]
 [33000 35000 37000 40000]]


In [34]:
#calculate yearly total of the stores
yearly_total = np.sum(sales_data[:,1:], axis=1) #so axis 0 means column wise calculation, and axis 1 means row wise calculation.
print(yearly_total)

[124000 131000 106000  93000 145000]


In [35]:
print("Yearly_total sum = ", np.sum(yearly_total))

Yearly_total sum =  599000


In [ ]:
#minimum sales per store
min_sales_per_store = np.min(sales_data[:,1:],axis=1) #store wise calculation is done, meaning row wise calculation of the matrix.
print(min_sales_per_store)

[25000 28000 22000 19000 33000]


In [39]:
#maximum sales for any store
max_sales  = np.max(sales_data[:, 1:], axis=0)
max_amount = np.max(max_sales)
print("Max Sales per year : ",max_sales)
print("Max Sales Number :", max_amount)

Max Sales per year :  [33000 35000 37000 40000]
Max Sales Number : 40000


In [41]:
#Now find out the cumulative sum for each store over the years
cumsum = np.cumsum(sales_data[:,1:], axis=1)
print("The cumulative sum row wise : \n", cumsum)

The cumulative sum row wise : 
 [[ 25000  55000  88000 124000]
 [ 28000  60000  94000 131000]
 [ 22000  47500  74500 106000]
 [ 19000  42000  66500  93000]
 [ 33000  68000 105000 145000]]
