# Learning about Numpy

In [2]:
import numpy as np

### Comparing speed of List and Numpy Array

In [3]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
end = time.time()
print("List Process completion time : ", end-start)

start = time.time()
np_array = np.arange(1000000) * 2
end = time.time()
print("np_array Process completion time : ", end-start)



List Process completion time :  0.029006242752075195
np_array Process completion time :  0.0008330345153808594


## Creating Array from scratch

In [10]:
#Filling the matrix with zeros
zeros = np.zeros((3,4))
print(zeros)

#filling the matrix with ones
ones = np.ones((3,2))
print(ones)

#filling up the matrix with the desired number
num = np.full((2,3),7)
print(num)

#filling up with random values
random_matrix = np.random.random((2,3))
print(random_matrix)

#making up an array
sequence = np.arange(0,20,2) #the parameters are start, stop, step and it doesn't include the outer bound
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.5485452  0.20228517 0.19825103]
 [0.1489677  0.6153643  0.16406175]]
[ 0  2  4  6  8 10 12 14 16 18]


## Vector, Matrix and Tensor