# Learning about Numpy

In [1]:
import numpy as np

### Comparing speed of List and Numpy Array

In [2]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
end = time.time()
print("List Process completion time : ", end-start)

start = time.time()
np_array = np.arange(1000000) * 2
end = time.time()
print("np_array Process completion time : ", end-start)



List Process completion time :  0.08798670768737793
np_array Process completion time :  0.011000633239746094


## Creating Array from scratch

In [3]:
#Filling the matrix with zeros
zeros = np.zeros((3,4))
print(zeros)

#filling the matrix with ones
ones = np.ones((3,2))
print(ones)

#filling up the matrix with the desired number
num = np.full((2,3),7)
print(num)

#filling up with random values
random_matrix = np.random.random((2,3))
print(random_matrix)

#making up an array
sequence = np.arange(0,20,2) #the parameters are start, stop, step and it doesn't include the outer bound
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.43940627 0.30086645 0.82230938]
 [0.36228915 0.70052193 0.41933916]]
[ 0  2  4  6  8 10 12 14 16 18]


## Vector, Matrix and Tensor

In [4]:
#Vector
vector = np.array([1,2,3]) #vector is like an array , 1 dimentional
print("vector : ", vector)

matrix = np.array([[1,2,3],
                   [3,4,5]]) #matrix is always a 2 dimentional array.
print("matrix : ", matrix)

tensor = np.array([[[1,2,3], [3,2,5]],
                    [[3,4,5],[5,3,9]]]) #tensor is always multidimentional , anything more than 2 dimentional is termed as tensor.
print("tensor : ", tensor)

vector :  [1 2 3]
matrix :  [[1 2 3]
 [3 4 5]]
tensor :  [[[1 2 3]
  [3 2 5]]

 [[3 4 5]
  [5 3 9]]]


## Array Properties

In [5]:
array = np.array()

TypeError: array() missing required argument 'object' (pos 0)